name: CI Testing

on:
  pull_request:
    branches:
      - master 
  
  push:
    branches:
      - master

jobs:
  test:
    name: Test on Node ${{ matrix.node-version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-${{ matrix.node-version }}-
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      - name: Install deps
        run: npm install
      - name: Linting
        run: npx ng lint
      - name: Build lib
        run: npx ng build ngx-ui-loader --prod
      - name: Testing
        run: npm test
      - name: Upload codecov report
        uses: codecov/codecov-action@v1
      - name: Production build
        run: npx ng build --prod
